{
 "title": "Power V2",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Todays Savings",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_monetary_aud{friendly_name=\"Today Solar Energy Savings\"}"
    }
   ]
  },
  {
   "title": "Todays Costs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_monetary_aud{friendly_name=\"Today Energy Total Cost\"}"
    }
   ]
  },
  {
   "title": "Max Power Produced",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max_over_time(hass_sensor_power_w{entity=\"sensor.solar_power_corrected\"}[1d])"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 14, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "hass_sensor_power_w{}", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Today",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_energy_kwh{friendly_name=\"Daily Consumption\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_sensor_energy_kwh{friendly_name=\"Daily Solar Energy\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "sum(hass_sensor_energy_kwh{friendly_name=~\"Daily Solar Consumed.+\"})",
     "legendFormat": "Daily Solar Consumed"
    },
    {
     "expr": "sum(hass_sensor_energy_kwh{friendly_name=~\"Daily Energy Import.+\"})",
     "legendFormat": "Daily Energy Imported"
    },
    {
     "expr": "hass_sensor_energy_kwh{friendly_name=~\"Daily Energy Export.+\"}",
     "legendFormat": "Daily Energy Exported"
    }
   ]
  },
  {
   "title": "This Month",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hass_sensor_energy_kwh{friendly_name=\"Monthly Consumption\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "hass_sensor_energy_kwh{friendly_name=\"Monthly Solar Energy\"}",
     "legendFormat": "{{friendly_name}}"
    },
    {
     "expr": "sum(hass_sensor_energy_kwh{friendly_name=~\"Monthly Solar Consumed.+\"})",
     "legendFormat": "Monthly Solar Consumed"
    },
    {
     "expr": "sum(hass_sensor_energy_kwh{friendly_name=~\"Monthly Energy Import.+\"})",
     "legendFormat": "Monthly Energy Imported"
    },
    {
     "expr": "sum(hass_sensor_energy_kwh{friendly_name=~\"Monthly Energy Export.+\"})",
     "legendFormat": "Monthly Energy Exported"
    }
   ]
  },
  {
   "title": "Consumption",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{friendly_name=~\"Daily Solar Consumed.+\"}[1h]))",
     "legendFormat": "Solar Consumed"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{friendly_name=~\"Daily Energy Import.+\"}[1h]))",
     "legendFormat": "Grid Import"
    }
   ]
  },
  {
   "title": "Solar Production",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{friendly_name=~\"Daily Solar Consumed.+\"}[1h]))",
     "legendFormat": "Solar Consumed"
    },
    {
     "expr": "sum(increase(hass_sensor_energy_kwh{friendly_name=\"Solar Energy Corrected\"}[1h]))",
     "legendFormat": "Solar Produced"
    }
   ]
  }
 ]
}