{
 "title": "Power Usage",
 "description": "Home assistant power metrics",
 "tags": [
  "Prometheus",
  "Energy"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Current Day Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_unit_kwh[$__range]))"
    }
   ]
  },
  {
   "title": "Current Month Power Total",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_unit_kwh[$__range]))"
    }
   ]
  },
  {
   "title": "Power Max last 24h",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "sum(hass_sensor_power_w)", "legendFormat": "Max Power" }
   ]
  },
  {
   "title": "Top 5 Devices Currently Running",
   "type": "stat",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(5,(hass_sensor_power_w > 5)))",
     "legendFormat": "{{ friendly_name }}"
    }
   ]
  },
  {
   "title": "Current Power",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hass_sensor_power_w)" },
    {}
   ]
  },
  {
   "title": "Top 5 Devices Last Week",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "topk(5,sum by (friendly_name) (increase(hass_sensor_unit_kwh[7d] )) )",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Current Day Power Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_unit_kwh[$__range])) * 0.253 + 0.781000"
    }
   ]
  },
  {
   "title": "Current Month Power Cost",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(hass_sensor_unit_kwh[$__range])) * 0.253 + 0.781000"
    }
   ]
  },
  {
   "title": "Total Devices",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "count(hass_sensor_power_w)" }
   ]
  },
  {
   "title": "Watts per hour",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(hass_sensor_power_w[1h]) * 24 / 1000 ",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  },
  {
   "title": "Month Power Total",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "hass_sensor_unit_kwh", "legendFormat": "{{ friendly_name }} " }
   ]
  },
  {
   "title": "Power Total",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "sum(hass_sensor_power_w)", "legendFormat": "Total" },
    { "expr": "hass_sensor_power_w", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "Current",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "sum(hass_sensor_current_a)", "legendFormat": "Total" },
    { "expr": "hass_sensor_current_a", "legendFormat": "{{friendly_name}}" }
   ]
  },
  {
   "title": "High Power Loads",
   "type": "graph",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 33 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "hass_sensor_power_w{friendly_name=~\"office desk power|washing machine power|tv unit power\"}",
     "legendFormat": "{{friendly_name}}"
    }
   ]
  }
 ]
}